### ISSUE TITLE
wg-net newsletter #1

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang-nursery/wg-net#51]
Let's collect content for the first issue of the Net Web WG newsletter here! :sparkles:

**Comment by levex** [comment]
I would definitely include the fact that we now have vision for each sub-WG!

**Comment by yoshuawuyts** [comment]
We should probably include two new framework releases:
- https://medium.com/@carllerche/tower-web-0-2-now-100-comment-attribute-free-3ed0633e47e5
- https://docs.rs/warp/0.1.2/warp/

**Comment by yoshuawuyts** [comment]
I'm thinking it might make more sense to send a newsletter from all the WGs. I'd be happy to coordinate this effort! Thinking of turning this into a post on https://internals.rust-lang.org.

**Comment by yoshuawuyts** [comment]
We talked about this with the WG leads on the Discord channel today, and the plan is to release the first Net WG newsletter on September 9th on https://internals.rust-lang.org. It was also brought up that we should find a way to archive the newsletters, so we should look into posting it to the Net WG blog too!

Please post any interesting net-related posts, projects and discussions you find so we can share them with the wider Rust community! :sparkles:

**Comment by aturon** [comment]
We should collect together all the recent news from futures and tokio (e.g. alpha4) for this edition.

**Comment by yoshuawuyts** [comment]
Wrote a first draft [link](https://paper.dropbox.com/doc/The-Network-Working-Group-Newsletter-1--AMnpGIExUiB36u3EKBVjrAZwAg-1A0vFfVuokYxCRSHkOBkv). Planning to publish tomorrow on `internals`. Feedback & edits would be very welcome!

cc/ @rust-lang-nursery/wg-net

**Comment by aturon** [comment]
Looks great -- thanks @yoshuawuyts!

**Comment by yoshuawuyts** [comment]
Published! https://internals.rust-lang.org/t/the-networking-working-group-newsletter-01/8391

Next newsletter: https://github.com/rust-lang-nursery/wg-net/issues/60
