### ISSUE TITLE
Blog Layout issue on Mobile

### ISSUE THREAD

**Issue by elpiel** [rust-lang-nursery/wg-net#63]
Reading one of the articles, I found out that the menu breaks the layout on Mobile.

*Chrome*
![chrome](https://user-images.githubusercontent.com/8925621/45869798-a4ed8980-bd89-11e8-9ab9-a6856cd69733.PNG)

*Firefox*
![firefox](https://user-images.githubusercontent.com/8925621/45869799-a4ed8980-bd89-11e8-8517-db12a47573ac.PNG)

**Comment by yoshuawuyts** [comment]
The relevant CSS for that seems to be here: https://github.com/rust-lang-nursery/wg-net/tree/gh-pages/_sass. A PR to fix these layout issues would be very welcome!

**Comment by elpiel** [comment]
You can assign me. I can fix it. Just wanted to open an issue first.

**Comment by elpiel** [comment]
Can somebody closes this? @yoshuawuyts maybe? The PR is merged.

**Comment by elpiel** [comment]
PR is merged and the issues are fixed.
