### ISSUE TITLE
areweasyncyet.rs

### ISSUE THREAD

**Issue by upsuper** [rust-lang-nursery/wg-net#86]
Hi, group!

I'm very interested in the progress of `async` support, but I found it hard to track the progress of all the separate features and prerequisites which are going through the process individually. So I made https://areweasyncyet.rs for that.

It would be appreciated if you can provide feedback for that, like maybe there are some other stuff you think worth being tracked there.

If the group wants to utilize this domain, I'm happy to donate it to you as well!

**Comment by upsuper** [comment]
Are async methods not going to stablized with async function? It sounds weird to me. I understand that there are some restrictions with `impl Trait` in trait method, which would affect async function as well, but I don't see why async wouldn't be supported with inherent functions. Is there anything I'm missing?

**Comment by Nemo157** [comment]
Async inherent methods work already and will almost certainly be stabilized along with async free functions, it's just async methods in traits that are blocked on design work (as well as the `impl Trait` returns from trait methods, I think there might be a little bit more design work for async methods in particular).

**Comment by yoshuawuyts** [comment]
> If the group wants to utilize this domain, I'm happy to donate it to you as well!

@upsuper we've been talking about this on Discord, we'd like to take you up on your offer!

There's a few options on how we could approach this, but my preference would be if you would join the [WG GitHub org](https://github.com/rust-net-web), and we could move the repo to be part of the org.

I feel you've done a stellar job in building this project! I would very much like to keep running the project the same way, which seems to be very open & collaborative.

How does this sound to you? Would this be something you're interested in? If yes, let me know and I will send you an invite! :sparkles:

**Comment by upsuper** [comment]
That sounds good to me. It's not very collaborative at the moment, but I'll try to make it more so (by adding more document about contributing, probably).

Please note that I may not have much bandwidth to involve in other activities of the working group, but I'm happy to run this project under the working group!

**Comment by yoshuawuyts** [comment]
@upsuper yay, I'm glad. I've sent you an invite!

**Comment by upsuper** [comment]
Transfer has been completed, it's now https://github.com/rust-net-web/areweasyncyet.rs!

Closing this issue.

**Comment by yoshuawuyts** [comment]
@upsuper yay, thanks heaps for that! I've also setup a team and granted you admin access on it. Hope it's all good! :tada:
